services:
  playwright:
    image: doubledie/playwright
    container_name: playwright-server
    build:
      context: .
      platforms:
        - "linux/amd64"
    volumes:
      - .:/app
    # For jupyter to be accessible outside the container
    ports:
      - "8888:8889"
      - "8889:8889"
    command: "jupyter lab --ip=0.0.0.0 --port=8889 --no-browser --allow-root"

